#!/usr/bin/env bash
shopt -u xpg_echo
json=$(cat)

declare -a seen
declare obj
declare level
key=( this )

function keypath() {
  echo -n ${key[0]} && [ ${#key[*]} -gt 1 ] && printf "[%s]" "${key[@]:1}"
}

while [[ ! -z "$json" ]]; do
  char=${json:0:1}

  if [[ $char =~ [[{] ]]; then
    level="${char}${level}"
    seen[${#level}-1]="$obj"
    seen[${#level}]="${char} "
    obj="${seen[${#level}]}"
    key[${#level}]=0
  elif [[ $char == '"' ]]; then
    value=$(expr "${json}" : '\("\(\(\([^\"]*\([\][^"]\)*\)*[\]"\)*\)*\([^"]\)*"\)')
    length=${#value}
    if [[ ${level:0:1} == '{' && ${obj: -2} != ': ' ]]; then
      key[${#level}]="$value"
      obj="${obj}${value}"
      unset value
    fi
    json="${json:$length-1}"
  elif [[ $char =~ [-0-9] ]]; then
    i=1
    while true; do [[ ${json:$i:1} =~ [0-9] ]] && let i=i+1 || break; done
    [[ ${json:$i:1} =~ [.] ]] && let i=i+1
    while true; do [[ ${json:$i:1} =~ [0-9] ]] && let i=i+1 || break; done
    [[ ${json:$i:1} =~ [eE] ]] && let i=i+1
    [[ ${json:$i:1} =~ [-+] ]] && let i=i+1
    while true; do [[ ${json:$i:1} =~ [0-9] ]] && let i=i+1 || break; done
    value="${json:0:$i}"
    json="${json:$i-1}"
  elif [[ $char =~ [tfn] ]]; then
    [[ $char == 'f' ]] && length=5 || length=4
    value="${json:0:$length}"
    [[ $value == 'true' || $value == 'null' || $value == 'false' ]] || exit 1
    json="${json:$length-1}"
  elif [[ $char =~ [:,] ]]; then
    [[ ${level:0:1} == '[' ]] && key[${#level}]=$[ ${key[${#level}]} + 1 ]
    obj="${obj}${char} "
  elif [[ $char =~ []}] ]]; then
    [[ "${char}" == '}' ]] && pair='{' || pair='['
    [[ "${obj}" != "${pair} " ]] && value="${obj} ${char}" || value="${pair} ${char}"
    level="${level:1}"
    obj="${seen[${#level}]}"
    unset key[${#level}+1]
  elif [[ ! $char =~ [[:space:]] ]]; then
    exit 1
  fi

  if [[ ! -z $value ]]; then
    echo "$(keypath): $value"
    obj="${obj}${value}"
    unset value
  fi
  json=${json:1}
done
